-- MySQL Script generated by MySQL Workbench
-- qua 15 jul 2020 19:23:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema newsDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `newsDatabase` ;

-- -----------------------------------------------------
-- Schema newsDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newsDatabase` DEFAULT CHARACTER SET utf8 ;
USE `newsDatabase` ;

-- -----------------------------------------------------
-- Table `newsDatabase`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsDatabase`.`news` ;

CREATE TABLE IF NOT EXISTS `newsDatabase`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `image` LONGTEXT NOT NULL,
  `text` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
